* Da fare domani

** Scrivere test suite per testare gli Schedule()

** BUG: scenario
- Città X ha fatto richiesta a familgia master per un package entro 5gg
- Dopo 3gg città X intercetta un pacco di una famiglia nemica
- Siccome il apcco intercettato è grande, dovresti disdire la richiesta alla famiglia master

In generale, quando per vie traverse una famiglia locale riesce ad impossessarsi di droga, deve ritirare la propria eventuale richiesta pregressa.

** Inizialmente, se ci sono molte città con droga=0, non ci sarà molta richiesta di droga. Definire il numero di dosi vendute in funzione della "richiesta" di droga nella città, ie. in base a da quanto è presente la mafia in quella città.


* Immediate

** Add "happiness" in cities
Depending on how steadily drugs is delivered, when needed

** Add basic AI

* Future

** Add concrete police

** Add mafia-wars when hold is low
*** When conquered, hold in neighbourgh friendly towns is increased exponentially with respect to the distance
*** Attacks should be scheduled and carried out in the next turn
