* Da fare domani

** Scrivere test suite per testare gli Schedule()

** BUG: scenario
- Città X ha fatto richiesta a familgia master per un package entro 5gg
- Dopo 3gg città X intercetta un pacco di una famiglia nemica
- Siccome il apcco intercettato è grande, dovresti disdire la richiesta alla famiglia master

In generale, quando per vie traverse una famiglia locale riesce ad impossessarsi di droga, deve ritirare la propria eventuale richiesta pregressa.

** Inizialmente, se ci sono molte città con droga=0, non ci sarà molta richiesta di droga. Definire il numero di dosi vendute in funzione della "richiesta" di droga nella città, ie. in base a da quanto è presente la mafia in quella città.


** Add contracts

- Local family =LF= acknowledges that there is need for drugs, and stipulate a "contract" with the main family =MF=:
  
  - =LF= pays 0$ upfront
  - =LF= will receive 1kg of drugs (hopefully) the next day
  - =MF= will pretend eg. 60% of the gain, to be received every week 
    
- Main family sends 1kg of drug for 1000$ to a local family. 
- That is delivered to the local family; +the local family will pay in advance, irregardless of what they will actually receive (maybe only when hold is low they will pretend payment at delivery)+
- After one week, the profit of =LF= will be "taxed" at 60%
- If =MF= does not deliver within 5 days, the hold of the family in that city will progressively get lower. In the meanwhile, =LF= will sell smaller doses
  

* Immediate

** Add drug demand from cities

Also: make local families ask main family for drug.

** Add "happiness" in cities
Depending on how steadily drugs is delivered, when needed


** Add basic AI

* Future

** Add concrete police

** Add mafia-wars when hold is low
